### ISSUE TITLE
Cannot build on Node v12

### ISSUE THREAD

**Issue by SlytherinCz** [ronomon/base64#1]
Nodejs v12.13.0
npm 6.12.0
node-gyp 5.0.5

```
> @ronomon/base64@2.4.1 install /home/***/Projects/***/node_modules/@ronomon/base64
> node-gyp rebuild

make: Entering directory '/home/***/Projects/***/node_modules/@ronomon/base64/build'
  CXX(target) Release/obj.target/binding/binding.o
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE decode(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:124:47: error: no matching function for call to ‘v8::Value::Uint32Value()’
   const uint32_t flags = info[2]->Uint32Value();
                                               ^
In file included from /home/***/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../nan/nan.h:54,
                 from ../binding.cc:1:
/home/***/.cache/node-gyp/12.13.0/include/node/v8.h:2611:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/***/.cache/node-gyp/12.13.0/include/node/v8.h:2611:41: note:   candidate expects 1 argument, 0 provided
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE encode(Nan::NAN_METHOD_ARGS_TYPE)’:
../binding.cc:234:47: error: no matching function for call to ‘v8::Value::Uint32Value()’
   const uint32_t flags = info[2]->Uint32Value();
                                               ^
In file included from /home/***/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../nan/nan.h:54,
                 from ../binding.cc:1:
/home/***/.cache/node-gyp/12.13.0/include/node/v8.h:2611:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^~~~~~~~~~~
/home/***/.cache/node-gyp/12.13.0/include/node/v8.h:2611:41: note:   candidate expects 1 argument, 0 provided
binding.target.mk:109: recipe for target 'Release/obj.target/binding/binding.o' failed
make: *** [Release/obj.target/binding/binding.o] Error 1
make: Leaving directory '/home/***/Projects/***/node_modules/@ronomon/base64/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/***/Projects/***/node_modules/@ronomon/base64
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ronomon/base64@2.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ronomon/base64@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by jorangreef** [comment]
Thanks @SlytherinCz, yes we need to move to N-API.

Please give me a few weeks and I will get to this.

**Comment by clocked0ne** [comment]
Hi, have you made any progress with updating this package to support NodeJS v12? AWS is moving lambdas to NodeJS v12 runtime and I would really like to be able to upgrade the lambdas my team have that use this package before AWS' support window shifts completely from NodeJS v8 in January:

> Deprecation schedule
> 
> AWS will be deprecating Node.js 8.10 according to the end of life schedule provided by the community. Node.js 8.10 will reach end of life on December 31, 2019. After January 6, 2020, you can no longer create a Node.js 8.10 Lambda function and the ability to update will be disabled after February 3, 2020. More information on can be found here.
> 
> Existing Node.js 8.10 functions can be migrated to the new runtime by making any necessary changes to code for compatibility with Node.js 12, and changing the function’s runtime configuration to “nodejs12.x”. Lambda functions running on Node.js 12 will have 2 full years of support.

**Comment by jorangreef** [comment]
@SlytherinCz and @clocked0ne, this is on my roadmap and I know it's important, but I am sorry I won't be able to get to this by end of December. It will take about a week of work, which I can't spare at the moment. If it's an emergency please drop me an email on joran@ronomon.com.

**Comment by clocked0ne** [comment]
Thanks for the update and appreciate your time. I'll keep checking back.

**Comment by rafaeelaudibert** [comment]
Hello! Any news on when you will be able to update this? Thanks for the library

**Comment by jakubwolny** [comment]
hey @jorangreef - would you maybe have a second to take a look at that PR? I think it does solve the problem of node v12 support
